name: ML4G_Proj1
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.0.5=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - debugpy=1.5.1=py38hfa26641_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - ipykernel=6.9.2=py38h7f3c49e_0
  - ipython=8.1.1=py38h578d9bd_0
  - jedi=0.18.1=pyhd8ed1ab_2
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.2=py38h578d9bd_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.82.0=h7bff187_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - liblapack=3.9.0=16_linux64_openblas
  - libnghttp2=1.47.0=h727a467_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libzlib=1.2.11=h166bdaf_1014
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - numpy=1.24.2=py38h10c12cc_0
  - openssl=1.1.1t=h7f8727e_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=21.2.4=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - psutil=5.9.0=py38h0a891b7_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybigwig=0.3.18=py38hf8a4f86_2
  - pygments=2.11.2=pyhd8ed1ab_0
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pyzmq=22.3.0=py38hfc09fa9_2
  - readline=8.1.2=h0f457ee_0
  - setuptools=58.0.4=py38h578d9bd_2
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.2=hc218d9a_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - tornado=6.1=py38h0a891b7_3
  - traitlets=5.1.1=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.11=h166bdaf_1014
  - pip:
      - appdirs==1.4.4
      - balanced-loss==0.1.0
      - charset-normalizer==3.1.0
      - click==8.0.4
      - cmake==3.26.0
      - docker-pycreds==0.4.0
      - filelock==3.10.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - idna==3.4
      - jinja2==3.1.2
      - joblib==1.2.0
      - lit==16.0.0
      - markupsafe==2.1.2
      - mpmath==1.3.0
      - networkx==3.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - pandas==1.5.3
      - pathtools==0.1.2
      - protobuf==4.22.1
      - pytz==2022.7.1
      - pyyaml==6.0
      - requests==2.28.2
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - sentry-sdk==1.18.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - sympy==1.11.1
      - threadpoolctl==3.1.0
      - torch==2.0.0
      - tqdm==4.65.0
      - triton==2.0.0
      - typing-extensions==4.5.0
      - urllib3==1.26.15
      - wandb==0.14.0
prefix: /data/student/workingdir/ML4G/.conda/envs/ML4G_Proj1
